### PR TITLE
Fix crate compilation on unix and windows.

### PR DESCRIPTION
**Pull request by Byron**
When trying to install using `cargo install unbox`, the crate doesn't compile anymore due to incompatible versions of Petgraph being mixed. This might have happened when a dependency using petgraph upgraded to a new minor version, but released itself using a patch.

The commits below are the small maintenance changes necessary to make it compile (mostly) without warnings and in the current crate ecosystem.

Thinking about it, it might be worth pinning the petgraph dependencies to prevent this from happening again.

### CODE REVIEW

**Comment by Byron** [comment]
~~Duplicate of #5~~ (_no dupe anymore, this one fixes windows too_), fixes #4

**Comment by mborejdo** [comment]
Unfortunately this PR still does not build on windows for me.

```
 unbox v0.2.0 (C:\Users\mib\.tools\git\checkouts\unbox-32c4eb876e634589\05f6a0f)
error[E0061]: this function takes 0 arguments but 1 argument was supplied
  --> src\formats\ar.rs:46:21
   |
46 |                     PathBuf::new(String::from_utf8(header.identifier())?)
   |                     ^^^^^^^^^^^^ --------------------------------------- supplied 1
argument
   |                     |
   |                     expected 0 arguments

error[E0308]: mismatched types
  --> src\formats\ar.rs:46:52
   |
46 |                     PathBuf::new(String::from_utf8(header.identifier())?)
   |                                                    ^^^^^^^^^^^^^^^^^^^
   |                                                    |
   |                                                    expected struct `std::vec::Vec`,
found `&[u8]`
   |                                                    help: try using a conversion method: `header.identifier().to_vec()`
   |
   = note: expected struct `std::vec::Vec<u8>`
           found reference `&[u8]`

warning: use of deprecated associated function `zip::read::ZipFile::<'a>::sanitized_name`: by stripping `..`s from the path, the meaning of paths can change.
                You must use a sanitization strategy that's appropriate for your input
  --> src\formats\zip.rs:44:29
   |
```

**Comment by Byron** [comment]
Please try again - I have  a feeling this conditional code never ran.

The issue was that OsStrings can't be crated from bytes on Windows, as these are UTF16 there, and thus there was a different way to get a `Path` from bytes.

**Comment by mborejdo** [comment]
Works now on current master. Thanks a lot and sorry for hijacking this PR to report problems :-)

**Comment by Byron** [comment]
I am glad you did! That way this PR can be what's needed to make `unbox` ready for a new release on crates.io.

**Comment by Byron** [comment]
I have created a now maintained fork of this tool called [`unpack`](https://crates.io/crates/unpack) as this project appears to be unmaintained.

**Pull request closed without merging**
